_BASE_: "Base-TotalText-Polygon.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
  ATTENTION:
    ENABLED: True
    IN_TRANSFORMER: True
    USE_GAUSSIAN: False
    windos_size: 7
  mode: 'cuda'
SOLVER:
  GAMMA: 0.1
  IMS_PER_BATCH: 4
  BASE_LR: 1e-6       # 1e-5
  LR_BACKBONE: 1e-7   # 1e-6
  WARMUP_ITERS: 2000
  STEPS: (19000, 34000)      # (200000,)
  MAX_ITER: 80000       # 20000
  CHECKPOINT_PERIOD: 1000
TEST:
  USE_LEXICON: False
  LEXICON_TYPE: 1
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/TESTR/totaltext/TESTR_Res50/TESTR_R50_Polygon_w7_4xb1_80000e_qkv_lr1e-6_test-2"

