_BASE_: "Base-Pretrain-Polygon.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
  ATTENTION:
    ENABLED: True
    IN_TRANSFORMER: True
    USE_GAUSSIAN: False
    windos_size: 7
  mode: 'cuda'
SOLVER:
  IMS_PER_BATCH: 4 # 8
  BASE_LR: 5e-5   # 1e-4
  LR_BACKBONE: 5e-6  # 1e-5
  WARMUP_ITERS: 0
  STEPS: (340000,)
  MAX_ITER: 440000
  CHECKPOINT_PERIOD: 10000
  GAMMA: 0.5
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/TESTR/pretrain/TESTR_R50_Polygon_w7_p8_4xb1_80000e"

